spring.application.name=asteroides

nasa.api.key=${API_KEY}

spring.security.oauth2.client.registration.google.client-id= ${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret= ${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email, profile

server.forward-headers-strategy=native
